"""initial schema

Revision ID: a68fbb4eb8ce
Revises: 
Create Date: 2026-03-23 07:51:01.587481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68fbb4eb8ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_entity', 'events', ['manuscript_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_events_manuscript_id'), 'events', ['manuscript_id'], unique=False)
    op.create_index('ix_events_manuscript_sequence', 'events', ['manuscript_id', 'sequence'], unique=False)
    op.create_table('manuscripts',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('controlling_design', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('BOOTSTRAPPING', 'PLANNING', 'DRAFTING', 'REVISING', 'COMPLETE', name='manuscriptstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acts',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('emotional_arc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('age', sa.String(length=100), nullable=True),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('motives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fears', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('desires', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secrets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('social_position', sa.Text(), nullable=False),
    sa.Column('speaking_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('movement_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recurring_gestures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('moral_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('arc_hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('arc_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_pov_character', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('associated_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('associated_conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('associated_character_tensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_density', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intensity_by_chapter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_embodiment_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overstatement_risk', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('act_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('function', sa.Text(), nullable=False),
    sa.Column('emotional_contour_target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transition_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opening_pressure', sa.Float(), nullable=False),
    sa.Column('closing_pressure', sa.Float(), nullable=False),
    sa.Column('thematic_density_target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rhythm_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('motif_target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('pov_character_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('time_marker', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('conflict', sa.Text(), nullable=False),
    sa.Column('stakes', sa.Text(), nullable=False),
    sa.Column('revelation', sa.Text(), nullable=True),
    sa.Column('emotional_turn', sa.Text(), nullable=False),
    sa.Column('dramatic_function', sa.String(length=200), nullable=False),
    sa.Column('expected_stylistic_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_device_functions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('themes_touched', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbols_touched', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_pivotal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DRAFTING', 'VALIDATING', 'REPAIRING', 'ACCEPTED', name='scenestatus', native_enum=False), nullable=False),
    sa.Column('accepted_draft_id', sa.UUID(), nullable=True),
    sa.Column('state_mutations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pov_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_profiles',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('voice_description', sa.Text(), nullable=False),
    sa.Column('directness', sa.Float(), nullable=False),
    sa.Column('subtext_target', sa.Float(), nullable=False),
    sa.Column('irony_target', sa.Float(), nullable=False),
    sa.Column('lyricism_target', sa.Float(), nullable=False),
    sa.Column('sentence_length_bands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentence_variance_bands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dialogue_density_band', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metaphor_density_band', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simile_density_band', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fragment_tolerance', sa.Float(), nullable=False),
    sa.Column('exposition_tolerance', sa.Float(), nullable=False),
    sa.Column('abstraction_tolerance', sa.Float(), nullable=False),
    sa.Column('preferred_imagery_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_imagery_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disfavoured_devices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recurrence_caps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chapter_modulation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_relationships',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('character_a_id', sa.UUID(), nullable=False),
    sa.Column('character_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'ended', 'transformed', name='rel_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_scene_states',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emotional_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intention_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_pressures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('arc_position', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promises',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PLOT', 'EMOTIONAL', 'THEMATIC', 'SYMBOLIC', 'TONAL', 'RHETORICAL', name='promisetype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('introducer_scene_id', sa.UUID(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('maturity_window_start', sa.Integer(), nullable=True),
    sa.Column('maturity_window_end', sa.Integer(), nullable=True),
    sa.Column('expected_resolution_window', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'MATURING', 'RESOLVED', 'ABANDONED', 'OVERDUE', name='promisestatus', native_enum=False), nullable=False),
    sa.Column('resolution_scene_id', sa.UUID(), nullable=True),
    sa.Column('payoff_strength', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['introducer_scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_dependencies',
    sa.Column('source_scene_id', sa.UUID(), nullable=False),
    sa.Column('target_scene_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('SETUP', 'PAYOFF', 'CONTINUITY', 'THEMATIC', 'SYMBOLIC', 'CAUSAL', name='dependencytype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_drafts',
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('branch_label', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prose', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('branch_status', sa.Enum('ACTIVE', 'SELECTED', 'PRUNED', name='branchstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_manifestations',
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=200), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('explicitness', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('absolute_time', sa.String(length=200), nullable=True),
    sa.Column('relative_time', sa.String(length=200), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consequences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_propagation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradiction_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_instances',
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('estimated_function', sa.String(length=200), nullable=False),
    sa.Column('speaker_character_id', sa.UUID(), nullable=True),
    sa.Column('imagery_domain', sa.String(length=200), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('intentional', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['scene_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promise_scene_links',
    sa.Column('promise_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('INTRODUCES', 'DEVELOPS', 'RESOLVES', name='promiselinktype', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promise_id'], ['promises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_vectors',
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('tension', sa.Float(), nullable=False),
    sa.Column('emotional_credibility', sa.Float(), nullable=False),
    sa.Column('prose_vitality', sa.Float(), nullable=False),
    sa.Column('voice_stability', sa.Float(), nullable=False),
    sa.Column('thematic_integration', sa.Float(), nullable=False),
    sa.Column('dialogue_quality', sa.Float(), nullable=False),
    sa.Column('redundancy_inverse', sa.Float(), nullable=False),
    sa.Column('stylistic_freshness', sa.Float(), nullable=False),
    sa.Column('transition_quality', sa.Float(), nullable=False),
    sa.Column('symbolic_restraint', sa.Float(), nullable=False),
    sa.Column('device_balance', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['scene_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_event_participants',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('participant', 'witness', 'informed', name='participant_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_results',
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('validator_type', sa.String(length=100), nullable=False),
    sa.Column('is_hard', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('span_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['scene_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_actions',
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_dimension', sa.String(length=200), nullable=False),
    sa.Column('target_span', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issue_reference_id', sa.UUID(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('preserve_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_interventions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_interventions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'APPLIED', 'VERIFIED', 'REVERTED', name='repairstatus', native_enum=False), nullable=False),
    sa.Column('result_draft_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['scene_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_reference_id'], ['validation_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_draft_id'], ['scene_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_actions')
    op.drop_table('validation_results')
    op.drop_table('timeline_event_participants')
    op.drop_table('score_vectors')
    op.drop_table('promise_scene_links')
    op.drop_table('device_instances')
    op.drop_table('timeline_events')
    op.drop_table('theme_manifestations')
    op.drop_table('scene_drafts')
    op.drop_table('scene_dependencies')
    op.drop_table('promises')
    op.drop_table('character_scene_states')
    op.drop_table('character_relationships')
    op.drop_table('style_profiles')
    op.drop_table('scenes')
    op.drop_table('chapters')
    op.drop_table('themes')
    op.drop_table('characters')
    op.drop_table('acts')
    op.drop_table('manuscripts')
    op.drop_index('ix_events_manuscript_sequence', table_name='events')
    op.drop_index(op.f('ix_events_manuscript_id'), table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
