"""Export manuscript as EPUB."""

from __future__ import annotations

import html
import re
import uuid
from pathlib import Path

from ebooklib import epub
from sqlalchemy.ext.asyncio import AsyncSession

from postwriter.canon.store import CanonStore
from postwriter.models.core import SceneDraft

BOOK_CSS = """
body {
    font-family: Georgia, "Times New Roman", serif;
    line-height: 1.7;
    margin: 2em;
    color: #1a1a1a;
}
h1 {
    font-size: 1.8em;
    margin-top: 2em;
    margin-bottom: 0.5em;
    font-weight: normal;
    text-align: center;
}
h2 {
    font-size: 1.3em;
    margin-top: 2em;
    margin-bottom: 0.5em;
    font-weight: normal;
    font-style: italic;
}
p {
    margin: 0.8em 0;
    text-align: justify;
    text-indent: 1.5em;
    hyphens: auto;
    -webkit-hyphens: auto;
}
p:first-of-type {
    text-indent: 0;
}
em {
    font-style: italic;
}
strong {
    font-weight: bold;
}
.scene-break {
    text-align: center;
    margin: 2em 0;
    font-size: 1.2em;
    color: #666;
    text-indent: 0;
}
.title-page {
    text-align: center;
    margin-top: 30%;
}
.title-page h1 {
    font-size: 2.5em;
    margin-bottom: 0.3em;
    font-weight: normal;
    letter-spacing: 0.05em;
}
.title-page .author {
    font-size: 1.2em;
    color: #555;
    margin-top: 1em;
    font-style: italic;
}
.title-page .generator {
    font-size: 0.8em;
    color: #999;
    margin-top: 3em;
}
.chapter-number {
    text-align: center;
    font-size: 0.9em;
    color: #999;
    margin-bottom: 0.2em;
    text-indent: 0;
    letter-spacing: 0.15em;
    text-transform: uppercase;
}
"""


async def export_epub(
    session: AsyncSession,
    manuscript_id: uuid.UUID,
    output_path: Path | None = None,
    author: str = "Postwriter",
    language: str = "en",
) -> Path | None:
    """Export the full manuscript as an EPUB file."""
    store = CanonStore(session)
    manuscript = await store.get_manuscript(manuscript_id)
    if not manuscript:
        return None

    title = manuscript.title or "Untitled"
    book = epub.EpubBook()

    # Metadata
    book.set_identifier(str(manuscript_id))
    book.set_title(title)
    book.set_language(language)
    book.add_author(author)

    # Stylesheet
    css = epub.EpubItem(
        uid="style",
        file_name="style/default.css",
        media_type="text/css",
        content=BOOK_CSS.encode("utf-8"),
    )
    book.add_item(css)

    # Title page
    title_html = (
        f'<div class="title-page">'
        f'<h1>{html.escape(title)}</h1>'
        f'<p class="author">{html.escape(author)}</p>'
        f'<p class="generator">Generated by Postwriter</p>'
        f'</div>'
    )
    title_page = epub.EpubHtml(
        title="Title Page",
        file_name="title.xhtml",
        lang=language,
    )
    title_page.content = title_html.encode("utf-8")
    title_page.add_item(css)
    book.add_item(title_page)

    # Build chapters
    chapters = await store.get_all_chapters(manuscript_id)
    epub_chapters = []
    spine = ["nav", title_page]

    for ch_idx, chapter in enumerate(chapters):
        ch_title = chapter.title or f"Chapter {chapter.ordinal}"
        scenes = await store.get_scenes(chapter.id)

        # Collect prose from accepted drafts
        scene_htmls = []
        for i, scene in enumerate(scenes):
            if scene.accepted_draft_id:
                draft = await session.get(SceneDraft, scene.accepted_draft_id)
                if draft and draft.prose:
                    paragraphs = _prose_to_html(draft.prose)
                    scene_htmls.append(paragraphs)
                    if i < len(scenes) - 1:
                        scene_htmls.append('<p class="scene-break">&#8226; &#8226; &#8226;</p>')

        if not scene_htmls:
            continue

        body = "\n".join(scene_htmls)
        chapter_heading = (
            f'<p class="chapter-number">Chapter {ch_idx + 1}</p>\n'
            f'<h1>{html.escape(ch_title)}</h1>\n'
        )
        content = chapter_heading + body

        ch = epub.EpubHtml(
            title=f"Chapter {ch_idx + 1}: {ch_title}",
            file_name=f"chapter_{chapter.ordinal:03d}.xhtml",
            lang=language,
        )
        ch.content = content.encode("utf-8")
        ch.add_item(css)

        book.add_item(ch)
        epub_chapters.append(ch)
        spine.append(ch)

    # Table of contents
    book.toc = [
        epub.Link("title.xhtml", "Title Page", "title"),
    ] + [
        epub.Link(ch.file_name, ch.title, ch.id)
        for ch in epub_chapters
    ]

    # Navigation
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # Spine
    book.spine = spine

    # Write
    if output_path is None:
        output_path = Path("output") / f"{_safe_filename(title)}.epub"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    epub.write_epub(str(output_path), book)

    return output_path


def _prose_to_html(prose: str) -> str:
    """Convert prose text to HTML paragraphs, handling markdown formatting."""
    lines = prose.strip().split("\n")
    paragraphs = []
    current: list[str] = []

    for line in lines:
        line = line.strip()
        if not line:
            if current:
                text = " ".join(current)
                paragraphs.append(f"<p>{_inline_markdown(text)}</p>")
                current = []
        else:
            current.append(line)

    if current:
        text = " ".join(current)
        paragraphs.append(f"<p>{_inline_markdown(text)}</p>")

    return "\n".join(paragraphs)


def _inline_markdown(text: str) -> str:
    """Convert inline markdown (bold, italic) to HTML, escaping the rest."""
    # First escape HTML entities in the raw text
    text = html.escape(text)

    # Bold+italic: ***text*** or ___text___
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', text)

    # Bold: **text** or __text__
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)

    # Italic: *text* or _text_ (but not mid-word underscores)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'(?<!\w)_(.+?)_(?!\w)', r'<em>\1</em>', text)

    # Em dash: convert -- to proper em dash if not already
    text = text.replace(' -- ', ' \u2014 ')
    text = text.replace('--', '\u2014')

    return text


def _safe_filename(title: str | None) -> str:
    if not title:
        return "manuscript"
    safe = re.sub(r"[^\w\s-]", "", title.lower())
    return re.sub(r"[\s]+", "-", safe).strip("-")[:50]
